# Generated by Django 3.0.8 on 2020-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
